spring:
  application:
    name: comment

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/daokhanhhuyen
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
    mongodb:
      uri: mongodb://admin:12345@localhost:27017/comment_db?authSource=admin
logging:
  level:
    org.mongodb.driver: WARN
    org.mongodb.driver.client: WARN
    org.springframework.data.mongodb: WARN
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

KEY:
  COMMENT:
    COUNT: POST_COMMENT_COUNT

server:
  port: 8085
